# Generated by Django 3.1.4 on 2021-03-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('product', models.CharField(max_length=1000)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
