# Generated by Django 3.1.4 on 2021-03-28 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Names',
        ),
    ]
